// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  DESKTOP-LBDLDSV
// DateTime: 5/23/2021 6:57:13 PM
// UserName: Valhari
// Input file <TCCL.grammar.y - 5/19/2021 6:28:11 PM>

// options: no-lines diagnose & report gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace ASTBuilder
{
internal enum Token {error=2,EOF=3,AND=4,ASTERISK=5,BANG=6,
    BOOLEAN=7,CLASS=8,COLON=9,COMMA=10,ELSE=11,EQUALS=12,
    HAT=13,IDENTIFIER=14,IF=15,INSTANCEOF=16,INT=17,INT_NUMBER=18,
    LBRACE=19,LBRACKET=20,LPAREN=21,MINUSOP=22,NEW=23,NULL=24,
    OP_EQ=25,OP_GE=26,OP_GT=27,OP_LAND=28,OP_LE=29,OP_LOR=30,
    OP_LT=31,OP_NE=32,PERCENT=33,PERIOD=34,PIPE=35,PLUSOP=36,
    PRIVATE=37,PUBLIC=38,QUESTION=39,RBRACE=40,RBRACKET=41,RETURN=42,
    RPAREN=43,RSLASH=44,SEMICOLON=45,STATIC=46,STRING_LITERAL=47,SUPER=48,
    STRUCT=49,THIS=50,TILDE=51,VOID=52,WHILE=53,UNARY=54};

// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal abstract class ScanBase : AbstractScanner<AbstractNode,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal class ScanObj {
  public int token;
  public AbstractNode yylval;
  public LexLocation yylloc;
  public ScanObj( int t, AbstractNode val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal partial class TCCLParser: ShiftReduceParser<AbstractNode, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[106];
  private static State[] states = new State[169];
  private static string[] nonTerms = new string[] {
      "CompilationUnit", "$accept", "ClassDeclaration", "Modifiers", "ClassBody", 
      "MemberDeclarations", "MemberDeclaration", "FieldDeclaration", "MethodDeclaration", 
      "ConstructorDeclaration", "StaticInitializer", "StructDeclaration", "TypeSpecifier", 
      "MethodSignature", "Block", "ParameterList", "Parameter", "FieldNames", 
      "TypeName", "ArraySpecifier", "PrimitiveType", "QualifiedName", "NameList", 
      "LocalItems", "LocalItem", "LocalVariableDeclaration", "Statement", "LocalVariableNames", 
      "EmptyStatement", "ExpressionStatement", "SelectionStatement", "IterationStatement", 
      "ReturnStatement", "Expression", "ArgumentList", "ArithmeticUnaryOperator", 
      "PrimaryExpression", "NotJustName", "SpecialName", "ComplexPrimary", "ComplexPrimaryNoParenthesis", 
      "Number", "FieldAccess", "MethodCall", "MethodReference", };

  static TCCLParser() {
    states[0] = new State(new int[]{38,115,37,116,46,117},new int[]{-1,1,-3,3,-4,4});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{8,5,38,112,37,113,46,114});
    states[5] = new State(new int[]{14,6});
    states[6] = new State(new int[]{19,8},new int[]{-5,7});
    states[7] = new State(-3);
    states[8] = new State(new int[]{40,167,38,115,37,116,46,161},new int[]{-6,9,-7,168,-8,12,-4,14,-9,163,-10,164,-11,165,-12,166});
    states[9] = new State(new int[]{40,10,38,115,37,116,46,161},new int[]{-7,11,-8,12,-4,14,-9,163,-10,164,-11,165,-12,166});
    states[10] = new State(-10);
    states[11] = new State(-13);
    states[12] = new State(new int[]{45,13});
    states[13] = new State(-14);
    states[14] = new State(new int[]{38,112,37,113,46,114,49,109,7,35,17,36,52,37,14,160},new int[]{-13,15,-14,158,-19,31,-21,34,-22,155,-20,106});
    states[15] = new State(new int[]{14,147},new int[]{-18,16,-14,17,-23,146});
    states[16] = new State(-26);
    states[17] = new State(new int[]{19,19},new int[]{-15,18});
    states[18] = new State(-19);
    states[19] = new State(new int[]{40,144,7,35,17,36,52,37,14,76,38,115,37,116,46,117,45,120,36,79,22,80,50,86,24,87,21,89,47,93,18,95,15,125,53,133,42,139,19,19},new int[]{-24,20,-25,145,-26,23,-13,24,-19,31,-21,34,-22,38,-20,106,-12,107,-4,108,-27,118,-29,119,-30,121,-34,122,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98,-31,124,-32,132,-33,138,-15,143});
    states[20] = new State(new int[]{40,21,7,35,17,36,52,37,14,76,38,115,37,116,46,117,45,120,36,79,22,80,50,86,24,87,21,89,47,93,18,95,15,125,53,133,42,139,19,19},new int[]{-25,22,-26,23,-13,24,-19,31,-21,34,-22,38,-20,106,-12,107,-4,108,-27,118,-29,119,-30,121,-34,122,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98,-31,124,-32,132,-33,138,-15,143});
    states[21] = new State(-40);
    states[22] = new State(-43);
    states[23] = new State(-44);
    states[24] = new State(new int[]{14,30},new int[]{-28,25,-23,27});
    states[25] = new State(new int[]{45,26});
    states[26] = new State(-46);
    states[27] = new State(new int[]{10,28,45,-48});
    states[28] = new State(new int[]{14,29});
    states[29] = new State(-37);
    states[30] = new State(-36);
    states[31] = new State(new int[]{20,32,14,-27});
    states[32] = new State(new int[]{41,33});
    states[33] = new State(-31);
    states[34] = new State(-29);
    states[35] = new State(-32);
    states[36] = new State(-33);
    states[37] = new State(-34);
    states[38] = new State(new int[]{34,39,12,41,20,-30,14,-30,45,-85,30,-85,28,-85,35,-85,13,-85,4,-85,25,-85,32,-85,27,-85,31,-85,29,-85,26,-85,36,-85,22,-85,5,-85,44,-85,33,-85,21,-99});
    states[39] = new State(new int[]{14,40});
    states[40] = new State(-102);
    states[41] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,42,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[42] = new State(new int[]{30,43,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,45,-64,43,-64,10,-64});
    states[43] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,44,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[44] = new State(new int[]{30,-65,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,45,-65,43,-65,10,-65});
    states[45] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,46,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[46] = new State(new int[]{30,-66,28,-66,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,45,-66,43,-66,10,-66});
    states[47] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,48,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[48] = new State(new int[]{30,-67,28,-67,35,-67,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,45,-67,43,-67,10,-67});
    states[49] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,50,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[50] = new State(new int[]{30,-68,28,-68,35,-68,13,-68,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,45,-68,43,-68,10,-68});
    states[51] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,52,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[52] = new State(new int[]{30,-69,28,-69,35,-69,13,-69,4,-69,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,45,-69,43,-69,10,-69});
    states[53] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,54,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[54] = new State(new int[]{30,-70,28,-70,35,-70,13,-70,4,-70,25,-70,32,-70,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,45,-70,43,-70,10,-70});
    states[55] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,56,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[56] = new State(new int[]{30,-71,28,-71,35,-71,13,-71,4,-71,25,-71,32,-71,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,45,-71,43,-71,10,-71});
    states[57] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,58,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[58] = new State(new int[]{30,-72,28,-72,35,-72,13,-72,4,-72,25,-72,32,-72,27,-72,31,-72,29,-72,26,-72,36,65,22,67,5,69,44,71,33,73,45,-72,43,-72,10,-72});
    states[59] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,60,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[60] = new State(new int[]{30,-73,28,-73,35,-73,13,-73,4,-73,25,-73,32,-73,27,-73,31,-73,29,-73,26,-73,36,65,22,67,5,69,44,71,33,73,45,-73,43,-73,10,-73});
    states[61] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,62,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[62] = new State(new int[]{30,-74,28,-74,35,-74,13,-74,4,-74,25,-74,32,-74,27,-74,31,-74,29,-74,26,-74,36,65,22,67,5,69,44,71,33,73,45,-74,43,-74,10,-74});
    states[63] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,64,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[64] = new State(new int[]{30,-75,28,-75,35,-75,13,-75,4,-75,25,-75,32,-75,27,-75,31,-75,29,-75,26,-75,36,65,22,67,5,69,44,71,33,73,45,-75,43,-75,10,-75});
    states[65] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,66,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[66] = new State(new int[]{30,-76,28,-76,35,-76,13,-76,4,-76,25,-76,32,-76,27,-76,31,-76,29,-76,26,-76,36,-76,22,-76,5,69,44,71,33,73,45,-76,43,-76,10,-76});
    states[67] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,68,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[68] = new State(new int[]{30,-77,28,-77,35,-77,13,-77,4,-77,25,-77,32,-77,27,-77,31,-77,29,-77,26,-77,36,-77,22,-77,5,69,44,71,33,73,45,-77,43,-77,10,-77});
    states[69] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,70,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[70] = new State(-78);
    states[71] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,72,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[72] = new State(-79);
    states[73] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,74,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[74] = new State(-80);
    states[75] = new State(new int[]{12,41,34,39,30,-85,28,-85,35,-85,13,-85,4,-85,25,-85,32,-85,27,-85,31,-85,29,-85,26,-85,36,-85,22,-85,5,-85,44,-85,33,-85,45,-85,43,-85,10,-85,21,-99});
    states[76] = new State(-101);
    states[77] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,78,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[78] = new State(-81);
    states[79] = new State(-83);
    states[80] = new State(-84);
    states[81] = new State(-82);
    states[82] = new State(new int[]{34,83,45,-86,30,-86,28,-86,35,-86,13,-86,4,-86,25,-86,32,-86,27,-86,31,-86,29,-86,26,-86,36,-86,22,-86,5,-86,44,-86,33,-86,43,-86,10,-86});
    states[83] = new State(new int[]{14,84});
    states[84] = new State(-95);
    states[85] = new State(new int[]{34,-87,45,-87,30,-87,28,-87,35,-87,13,-87,4,-87,25,-87,32,-87,27,-87,31,-87,29,-87,26,-87,36,-87,22,-87,5,-87,44,-87,33,-87,43,-87,10,-87,21,-100});
    states[86] = new State(-103);
    states[87] = new State(-104);
    states[88] = new State(-88);
    states[89] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,90,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[90] = new State(new int[]{43,91,30,43,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73});
    states[91] = new State(-89);
    states[92] = new State(new int[]{34,-90,45,-90,30,-90,28,-90,35,-90,13,-90,4,-90,25,-90,32,-90,27,-90,31,-90,29,-90,26,-90,36,-90,22,-90,5,-90,44,-90,33,-90,43,-90,10,-90,21,-98});
    states[93] = new State(-91);
    states[94] = new State(-92);
    states[95] = new State(-105);
    states[96] = new State(-93);
    states[97] = new State(-94);
    states[98] = new State(new int[]{21,99});
    states[99] = new State(new int[]{43,104,14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-35,100,-34,105,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[100] = new State(new int[]{43,101,10,102});
    states[101] = new State(-96);
    states[102] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,103,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[103] = new State(new int[]{30,43,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,43,-63,10,-63});
    states[104] = new State(-97);
    states[105] = new State(new int[]{30,43,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73,43,-62,10,-62});
    states[106] = new State(-28);
    states[107] = new State(-47);
    states[108] = new State(new int[]{49,109,38,112,37,113,46,114});
    states[109] = new State(new int[]{14,110});
    states[110] = new State(new int[]{19,8},new int[]{-5,111});
    states[111] = new State(-25);
    states[112] = new State(-7);
    states[113] = new State(-8);
    states[114] = new State(-9);
    states[115] = new State(-4);
    states[116] = new State(-5);
    states[117] = new State(-6);
    states[118] = new State(-45);
    states[119] = new State(-49);
    states[120] = new State(-55);
    states[121] = new State(-50);
    states[122] = new State(new int[]{45,123,30,43,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73});
    states[123] = new State(-56);
    states[124] = new State(-51);
    states[125] = new State(new int[]{21,126});
    states[126] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,127,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[127] = new State(new int[]{43,128,30,43,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73});
    states[128] = new State(new int[]{45,120,14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95,15,125,53,133,42,139,19,19},new int[]{-27,129,-29,119,-30,121,-34,122,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98,-31,124,-32,132,-33,138,-15,143});
    states[129] = new State(new int[]{11,130,40,-58,7,-58,17,-58,52,-58,14,-58,38,-58,37,-58,46,-58,45,-58,36,-58,22,-58,50,-58,24,-58,21,-58,47,-58,18,-58,15,-58,53,-58,42,-58,19,-58});
    states[130] = new State(new int[]{45,120,14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95,15,125,53,133,42,139,19,19},new int[]{-27,131,-29,119,-30,121,-34,122,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98,-31,124,-32,132,-33,138,-15,143});
    states[131] = new State(-57);
    states[132] = new State(-52);
    states[133] = new State(new int[]{21,134});
    states[134] = new State(new int[]{14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,135,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[135] = new State(new int[]{43,136,30,43,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73});
    states[136] = new State(new int[]{45,120,14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95,15,125,53,133,42,139,19,19},new int[]{-27,137,-29,119,-30,121,-34,122,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98,-31,124,-32,132,-33,138,-15,143});
    states[137] = new State(-59);
    states[138] = new State(-53);
    states[139] = new State(new int[]{45,142,14,76,36,79,22,80,50,86,24,87,21,89,47,93,18,95},new int[]{-34,140,-22,75,-36,77,-37,81,-38,82,-39,85,-40,88,-41,92,-42,94,-43,96,-44,97,-45,98});
    states[140] = new State(new int[]{45,141,30,43,28,45,35,47,13,49,4,51,25,53,32,55,27,57,31,59,29,61,26,63,36,65,22,67,5,69,44,71,33,73});
    states[141] = new State(-60);
    states[142] = new State(-61);
    states[143] = new State(-54);
    states[144] = new State(-41);
    states[145] = new State(-42);
    states[146] = new State(new int[]{10,28,45,-35});
    states[147] = new State(new int[]{21,148,10,-36,45,-36});
    states[148] = new State(new int[]{43,156,7,35,17,36,52,37,14,76},new int[]{-16,149,-17,157,-13,153,-19,31,-21,34,-22,155,-20,106});
    states[149] = new State(new int[]{43,150,10,151});
    states[150] = new State(-20);
    states[151] = new State(new int[]{7,35,17,36,52,37,14,76},new int[]{-17,152,-13,153,-19,31,-21,34,-22,155,-20,106});
    states[152] = new State(-23);
    states[153] = new State(new int[]{14,154});
    states[154] = new State(-24);
    states[155] = new State(new int[]{34,39,20,-30,14,-30});
    states[156] = new State(-21);
    states[157] = new State(-22);
    states[158] = new State(new int[]{19,19},new int[]{-15,159});
    states[159] = new State(-38);
    states[160] = new State(new int[]{21,148,34,-101,20,-101,14,-101});
    states[161] = new State(new int[]{19,19,38,-6,37,-6,46,-6,49,-6,7,-6,17,-6,52,-6,14,-6},new int[]{-15,162});
    states[162] = new State(-39);
    states[163] = new State(-15);
    states[164] = new State(-16);
    states[165] = new State(-17);
    states[166] = new State(-18);
    states[167] = new State(-11);
    states[168] = new State(-12);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{-4,8,14,-5});
    rules[4] = new Rule(-4, new int[]{38});
    rules[5] = new Rule(-4, new int[]{37});
    rules[6] = new Rule(-4, new int[]{46});
    rules[7] = new Rule(-4, new int[]{-4,38});
    rules[8] = new Rule(-4, new int[]{-4,37});
    rules[9] = new Rule(-4, new int[]{-4,46});
    rules[10] = new Rule(-5, new int[]{19,-6,40});
    rules[11] = new Rule(-5, new int[]{19,40});
    rules[12] = new Rule(-6, new int[]{-7});
    rules[13] = new Rule(-6, new int[]{-6,-7});
    rules[14] = new Rule(-7, new int[]{-8,45});
    rules[15] = new Rule(-7, new int[]{-9});
    rules[16] = new Rule(-7, new int[]{-10});
    rules[17] = new Rule(-7, new int[]{-11});
    rules[18] = new Rule(-7, new int[]{-12});
    rules[19] = new Rule(-9, new int[]{-4,-13,-14,-15});
    rules[20] = new Rule(-14, new int[]{14,21,-16,43});
    rules[21] = new Rule(-14, new int[]{14,21,43});
    rules[22] = new Rule(-16, new int[]{-17});
    rules[23] = new Rule(-16, new int[]{-16,10,-17});
    rules[24] = new Rule(-17, new int[]{-13,14});
    rules[25] = new Rule(-12, new int[]{-4,49,14,-5});
    rules[26] = new Rule(-8, new int[]{-4,-13,-18});
    rules[27] = new Rule(-13, new int[]{-19});
    rules[28] = new Rule(-13, new int[]{-20});
    rules[29] = new Rule(-19, new int[]{-21});
    rules[30] = new Rule(-19, new int[]{-22});
    rules[31] = new Rule(-20, new int[]{-19,20,41});
    rules[32] = new Rule(-21, new int[]{7});
    rules[33] = new Rule(-21, new int[]{17});
    rules[34] = new Rule(-21, new int[]{52});
    rules[35] = new Rule(-18, new int[]{-23});
    rules[36] = new Rule(-23, new int[]{14});
    rules[37] = new Rule(-23, new int[]{-23,10,14});
    rules[38] = new Rule(-10, new int[]{-4,-14,-15});
    rules[39] = new Rule(-11, new int[]{46,-15});
    rules[40] = new Rule(-15, new int[]{19,-24,40});
    rules[41] = new Rule(-15, new int[]{19,40});
    rules[42] = new Rule(-24, new int[]{-25});
    rules[43] = new Rule(-24, new int[]{-24,-25});
    rules[44] = new Rule(-25, new int[]{-26});
    rules[45] = new Rule(-25, new int[]{-27});
    rules[46] = new Rule(-26, new int[]{-13,-28,45});
    rules[47] = new Rule(-26, new int[]{-12});
    rules[48] = new Rule(-28, new int[]{-23});
    rules[49] = new Rule(-27, new int[]{-29});
    rules[50] = new Rule(-27, new int[]{-30});
    rules[51] = new Rule(-27, new int[]{-31});
    rules[52] = new Rule(-27, new int[]{-32});
    rules[53] = new Rule(-27, new int[]{-33});
    rules[54] = new Rule(-27, new int[]{-15});
    rules[55] = new Rule(-29, new int[]{45});
    rules[56] = new Rule(-30, new int[]{-34,45});
    rules[57] = new Rule(-31, new int[]{15,21,-34,43,-27,11,-27});
    rules[58] = new Rule(-31, new int[]{15,21,-34,43,-27});
    rules[59] = new Rule(-32, new int[]{53,21,-34,43,-27});
    rules[60] = new Rule(-33, new int[]{42,-34,45});
    rules[61] = new Rule(-33, new int[]{42,45});
    rules[62] = new Rule(-35, new int[]{-34});
    rules[63] = new Rule(-35, new int[]{-35,10,-34});
    rules[64] = new Rule(-34, new int[]{-22,12,-34});
    rules[65] = new Rule(-34, new int[]{-34,30,-34});
    rules[66] = new Rule(-34, new int[]{-34,28,-34});
    rules[67] = new Rule(-34, new int[]{-34,35,-34});
    rules[68] = new Rule(-34, new int[]{-34,13,-34});
    rules[69] = new Rule(-34, new int[]{-34,4,-34});
    rules[70] = new Rule(-34, new int[]{-34,25,-34});
    rules[71] = new Rule(-34, new int[]{-34,32,-34});
    rules[72] = new Rule(-34, new int[]{-34,27,-34});
    rules[73] = new Rule(-34, new int[]{-34,31,-34});
    rules[74] = new Rule(-34, new int[]{-34,29,-34});
    rules[75] = new Rule(-34, new int[]{-34,26,-34});
    rules[76] = new Rule(-34, new int[]{-34,36,-34});
    rules[77] = new Rule(-34, new int[]{-34,22,-34});
    rules[78] = new Rule(-34, new int[]{-34,5,-34});
    rules[79] = new Rule(-34, new int[]{-34,44,-34});
    rules[80] = new Rule(-34, new int[]{-34,33,-34});
    rules[81] = new Rule(-34, new int[]{-36,-34});
    rules[82] = new Rule(-34, new int[]{-37});
    rules[83] = new Rule(-36, new int[]{36});
    rules[84] = new Rule(-36, new int[]{22});
    rules[85] = new Rule(-37, new int[]{-22});
    rules[86] = new Rule(-37, new int[]{-38});
    rules[87] = new Rule(-38, new int[]{-39});
    rules[88] = new Rule(-38, new int[]{-40});
    rules[89] = new Rule(-40, new int[]{21,-34,43});
    rules[90] = new Rule(-40, new int[]{-41});
    rules[91] = new Rule(-41, new int[]{47});
    rules[92] = new Rule(-41, new int[]{-42});
    rules[93] = new Rule(-41, new int[]{-43});
    rules[94] = new Rule(-41, new int[]{-44});
    rules[95] = new Rule(-43, new int[]{-38,34,14});
    rules[96] = new Rule(-44, new int[]{-45,21,-35,43});
    rules[97] = new Rule(-44, new int[]{-45,21,43});
    rules[98] = new Rule(-45, new int[]{-41});
    rules[99] = new Rule(-45, new int[]{-22});
    rules[100] = new Rule(-45, new int[]{-39});
    rules[101] = new Rule(-22, new int[]{14});
    rules[102] = new Rule(-22, new int[]{-22,34,14});
    rules[103] = new Rule(-39, new int[]{50});
    rules[104] = new Rule(-39, new int[]{24});
    rules[105] = new Rule(-42, new int[]{18});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Token.error, (int)Token.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // CompilationUnit -> ClassDeclaration
{ CurrentSemanticValue = new CompilationUnit(ValueStack[ValueStack.Depth-1]);}
        break;
      case 3: // ClassDeclaration -> Modifiers, CLASS, IDENTIFIER, ClassBody
{ CurrentSemanticValue = new ClassDeclaration(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]);}
        break;
      case 4: // Modifiers -> PUBLIC
{ CurrentSemanticValue = new Modifiers(ModifierType.PUBLIC);}
        break;
      case 5: // Modifiers -> PRIVATE
{ CurrentSemanticValue = new Modifiers(ModifierType.PRIVATE);}
        break;
      case 6: // Modifiers -> STATIC
{ CurrentSemanticValue = new Modifiers(ModifierType.STATIC);}
        break;
      case 7: // Modifiers -> Modifiers, PUBLIC
{ ((Modifiers) ValueStack[ValueStack.Depth-2]).AddModType(ModifierType.PUBLIC);}
        break;
      case 8: // Modifiers -> Modifiers, PRIVATE
{ ((Modifiers) ValueStack[ValueStack.Depth-2]).AddModType(ModifierType.PRIVATE);}
        break;
      case 9: // Modifiers -> Modifiers, STATIC
{ ((Modifiers) ValueStack[ValueStack.Depth-2]).AddModType(ModifierType.STATIC);}
        break;
      case 10: // ClassBody -> LBRACE, MemberDeclarations, RBRACE
{ CurrentSemanticValue = new ClassBody(ValueStack[ValueStack.Depth-2]);}
        break;
      case 11: // ClassBody -> LBRACE, RBRACE
{ CurrentSemanticValue = new ClassBody();}
        break;
      case 12: // MemberDeclarations -> MemberDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 13: // MemberDeclarations -> MemberDeclarations, MemberDeclaration
{ ValueStack[ValueStack.Depth-2].makeSibling(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-2];}
        break;
      case 14: // MemberDeclaration -> FieldDeclaration, SEMICOLON
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2];}
        break;
      case 15: // MemberDeclaration -> MethodDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 16: // MemberDeclaration -> ConstructorDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 17: // MemberDeclaration -> StaticInitializer
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 18: // MemberDeclaration -> StructDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 19: // MethodDeclaration -> Modifiers, TypeSpecifier, MethodSignature, Block
{CurrentSemanticValue = new MethodDeclaration(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 20: // MethodSignature -> IDENTIFIER, LPAREN, ParameterList, RPAREN
{ CurrentSemanticValue = new MethodSignature(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2]); }
        break;
      case 21: // MethodSignature -> IDENTIFIER, LPAREN, RPAREN
{ CurrentSemanticValue = new MethodSignature(ValueStack[ValueStack.Depth-3]); }
        break;
      case 22: // ParameterList -> Parameter
{ CurrentSemanticValue = new ParameterList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 23: // ParameterList -> ParameterList, COMMA, Parameter
{ ValueStack[ValueStack.Depth-3].adoptChildren(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3];}
        break;
      case 24: // Parameter -> TypeSpecifier, IDENTIFIER
{ CurrentSemanticValue = new Parameter(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 25: // StructDeclaration -> Modifiers, STRUCT, IDENTIFIER, ClassBody
{ CurrentSemanticValue = new StructDeclaration(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]);}
        break;
      case 26: // FieldDeclaration -> Modifiers, TypeSpecifier, FieldNames
{CurrentSemanticValue =  new FieldDeclaration(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]);}
        break;
      case 27: // TypeSpecifier -> TypeName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 28: // TypeSpecifier -> ArraySpecifier
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 29: // TypeName -> PrimitiveType
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 30: // TypeName -> QualifiedName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 31: // ArraySpecifier -> TypeName, LBRACKET, RBRACKET
{ CurrentSemanticValue = new ArraySpecifier(ValueStack[ValueStack.Depth-3]); }
        break;
      case 32: // PrimitiveType -> BOOLEAN
{ CurrentSemanticValue = new PrimitiveType(EnumPrimitiveType.BOOLEAN); }
        break;
      case 33: // PrimitiveType -> INT
{ CurrentSemanticValue = new PrimitiveType(EnumPrimitiveType.INT); }
        break;
      case 34: // PrimitiveType -> VOID
{ CurrentSemanticValue = new PrimitiveType(EnumPrimitiveType.VOID); }
        break;
      case 35: // FieldNames -> NameList
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 36: // NameList -> IDENTIFIER
{ CurrentSemanticValue = new NameList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 37: // NameList -> NameList, COMMA, IDENTIFIER
{ ValueStack[ValueStack.Depth-3].adoptChildren(ValueStack[ValueStack.Depth-1]); }
        break;
      case 38: // ConstructorDeclaration -> Modifiers, MethodSignature, Block
{ CurrentSemanticValue = new ConstructorDeclaration(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 39: // StaticInitializer -> STATIC, Block
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 40: // Block -> LBRACE, LocalItems, RBRACE
{ CurrentSemanticValue = new Block(ValueStack[ValueStack.Depth-2]);}
        break;
      case 41: // Block -> LBRACE, RBRACE
{ CurrentSemanticValue =  new Block(); }
        break;
      case 42: // LocalItems -> LocalItem
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 43: // LocalItems -> LocalItems, LocalItem
{ ValueStack[ValueStack.Depth-2].makeSibling(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-2];}
        break;
      case 44: // LocalItem -> LocalVariableDeclaration
{ CurrentSemanticValue =  ValueStack[ValueStack.Depth-1]; }
        break;
      case 45: // LocalItem -> Statement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 46: // LocalVariableDeclaration -> TypeSpecifier, LocalVariableNames, SEMICOLON
{ CurrentSemanticValue = new LocalVariableDeclaration(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2]); }
        break;
      case 47: // LocalVariableDeclaration -> StructDeclaration
{ CurrentSemanticValue = new LocalVariableDeclaration(ValueStack[ValueStack.Depth-1]); }
        break;
      case 48: // LocalVariableNames -> NameList
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 49: // Statement -> EmptyStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 50: // Statement -> ExpressionStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 51: // Statement -> SelectionStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 52: // Statement -> IterationStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 53: // Statement -> ReturnStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 54: // Statement -> Block
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 55: // EmptyStatement -> SEMICOLON
{ CurrentSemanticValue = new  EmptyStatement(); }
        break;
      case 56: // ExpressionStatement -> Expression, SEMICOLON
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2];}
        break;
      case 57: // SelectionStatement -> IF, LPAREN, Expression, RPAREN, Statement, ELSE, 
               //                       Statement
{ CurrentSemanticValue = new SelectionStatement(ValueStack[ValueStack.Depth-5], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 58: // SelectionStatement -> IF, LPAREN, Expression, RPAREN, Statement
{ CurrentSemanticValue = new SelectionStatement(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 59: // IterationStatement -> WHILE, LPAREN, Expression, RPAREN, Statement
{ CurrentSemanticValue = new IterationStatement(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 60: // ReturnStatement -> RETURN, Expression, SEMICOLON
{ CurrentSemanticValue = new ReturnStatement(ValueStack[ValueStack.Depth-2]); }
        break;
      case 61: // ReturnStatement -> RETURN, SEMICOLON
{ CurrentSemanticValue = new ReturnStatement(); }
        break;
      case 62: // ArgumentList -> Expression
{ CurrentSemanticValue = new ArgumentList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 63: // ArgumentList -> ArgumentList, COMMA, Expression
{ ValueStack[ValueStack.Depth-3].adoptChildren(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3];}
        break;
      case 64: // Expression -> QualifiedName, EQUALS, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.EQUALS, ValueStack[ValueStack.Depth-1]); }
        break;
      case 65: // Expression -> Expression, OP_LOR, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_LOR, ValueStack[ValueStack.Depth-1]); }
        break;
      case 66: // Expression -> Expression, OP_LAND, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_LAND, ValueStack[ValueStack.Depth-1]); }
        break;
      case 67: // Expression -> Expression, PIPE, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.PIPE, ValueStack[ValueStack.Depth-1]); }
        break;
      case 68: // Expression -> Expression, HAT, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.HAT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 69: // Expression -> Expression, AND, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.AND, ValueStack[ValueStack.Depth-1]); }
        break;
      case 70: // Expression -> Expression, OP_EQ, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_EQ, ValueStack[ValueStack.Depth-1]); }
        break;
      case 71: // Expression -> Expression, OP_NE, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_NE, ValueStack[ValueStack.Depth-1]); }
        break;
      case 72: // Expression -> Expression, OP_GT, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_GT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 73: // Expression -> Expression, OP_LT, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_LT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 74: // Expression -> Expression, OP_LE, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_LE, ValueStack[ValueStack.Depth-1]); }
        break;
      case 75: // Expression -> Expression, OP_GE, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_GE, ValueStack[ValueStack.Depth-1]); }
        break;
      case 76: // Expression -> Expression, PLUSOP, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.PLUSOP, ValueStack[ValueStack.Depth-1]); }
        break;
      case 77: // Expression -> Expression, MINUSOP, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.MINUSOP, ValueStack[ValueStack.Depth-1]); }
        break;
      case 78: // Expression -> Expression, ASTERISK, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.ASTERISK, ValueStack[ValueStack.Depth-1]); }
        break;
      case 79: // Expression -> Expression, RSLASH, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.RSLASH, ValueStack[ValueStack.Depth-1]); }
        break;
      case 80: // Expression -> Expression, PERCENT, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.PERCENT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 81: // Expression -> ArithmeticUnaryOperator, Expression
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; CurrentSemanticValue.adoptChildren(ValueStack[ValueStack.Depth-1]); }
        break;
      case 82: // Expression -> PrimaryExpression
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 83: // ArithmeticUnaryOperator -> PLUSOP
{ CurrentSemanticValue = new Expression(ExprKind.PLUSOP); }
        break;
      case 84: // ArithmeticUnaryOperator -> MINUSOP
{ CurrentSemanticValue = new Expression(ExprKind.MINUSOP); }
        break;
      case 85: // PrimaryExpression -> QualifiedName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 86: // PrimaryExpression -> NotJustName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 87: // NotJustName -> SpecialName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 88: // NotJustName -> ComplexPrimary
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 89: // ComplexPrimary -> LPAREN, Expression, RPAREN
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2];}
        break;
      case 90: // ComplexPrimary -> ComplexPrimaryNoParenthesis
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 91: // ComplexPrimaryNoParenthesis -> STRING_LITERAL
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 92: // ComplexPrimaryNoParenthesis -> Number
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 93: // ComplexPrimaryNoParenthesis -> FieldAccess
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 94: // ComplexPrimaryNoParenthesis -> MethodCall
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 95: // FieldAccess -> NotJustName, PERIOD, IDENTIFIER
{ CurrentSemanticValue = new FieldAccess(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]);}
        break;
      case 96: // MethodCall -> MethodReference, LPAREN, ArgumentList, RPAREN
{ CurrentSemanticValue =  new MethodCall(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2]); }
        break;
      case 97: // MethodCall -> MethodReference, LPAREN, RPAREN
{ CurrentSemanticValue = new MethodCall(ValueStack[ValueStack.Depth-3]);}
        break;
      case 98: // MethodReference -> ComplexPrimaryNoParenthesis
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 99: // MethodReference -> QualifiedName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 100: // MethodReference -> SpecialName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 101: // QualifiedName -> IDENTIFIER
{ CurrentSemanticValue = new QualifiedName(ValueStack[ValueStack.Depth-1]); }
        break;
      case 102: // QualifiedName -> QualifiedName, PERIOD, IDENTIFIER
{ ValueStack[ValueStack.Depth-3].adoptChildren(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
        break;
      case 103: // SpecialName -> THIS
{ CurrentSemanticValue = new SpecialName(ReservedNames.THIS); }
        break;
      case 104: // SpecialName -> NULL
{ CurrentSemanticValue = new SpecialName(ReservedNames.NULL); }
        break;
      case 105: // Number -> INT_NUMBER
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Token)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Token)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


}
}
